# Generated by Django 4.1.1 on 2022-10-26 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_alter_like_post_alter_like_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='body',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.CharField(default='', max_length=200),
        ),
    ]
