# Generated by Django 4.1.1 on 2022-10-26 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0008_remove_comment_body_comment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='liked',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
