# Generated by Django 4.1.1 on 2022-10-27 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_comment_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='click_post',
            field=models.BooleanField(default=True),
        ),
    ]
